language: objective-c
xcode_workspace: test.xcworkspace # path to your xcodeproj folder
xcode_scheme: test
xcode_destination: platform=iOS Simulator,OS=11.1,name=iPhone X
notifications:
  slack:
    on_success: always